import type { CollectionConfig } from 'payload'
import { revalidateTag } from 'next/cache'
import { isEditor, publishedOnly } from '@/access/roles'
import { CACHE_TAGS } from '@/lib/cache-tags'

export const BlogPosts: CollectionConfig = {
  slug: 'blog-posts',
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['title', 'author', 'publishedDate', '_status'],
  },
  versions: {
    drafts: {
      autosave: true,
    },
  },
  access: {
    read: publishedOnly,
    create: isEditor,
    update: isEditor,
    delete: isEditor,
  },
  hooks: {
    afterChange: [() => revalidateTag(CACHE_TAGS.blogPosts, 'default')],
    afterDelete: [() => revalidateTag(CACHE_TAGS.blogPosts, 'default')],
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
    },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
      index: true,
    },
    {
      name: 'author',
      type: 'text',
      required: true,
    },
    {
      name: 'publishedDate',
      type: 'date',
      required: true,
      defaultValue: () => new Date().toISOString(),
      admin: {
        date: {
          pickerAppearance: 'dayOnly',
        },
      },
    },
    {
      name: 'featuredImage',
      type: 'upload',
      relationTo: 'media',
    },
    {
      name: 'sermonSeries',
      type: 'relationship',
      relationTo: 'sermon-series',
      admin: {
        description: 'Optionally link to a sermon series',
      },
    },
    {
      name: 'sermon',
      type: 'relationship',
      relationTo: 'sermons',
      admin: {
        description: 'Source sermon (for AI-generated posts)',
      },
    },
    {
      name: 'isAiGenerated',
      type: 'checkbox',
      defaultValue: false,
      admin: {
        readOnly: true,
        description: 'Whether this post was generated by AI from a sermon transcript',
      },
    },
    {
      name: 'aiDisclosure',
      type: 'text',
      defaultValue:
        'This content was generated by AI from a sermon recording and reviewed for accuracy.',
      admin: {
        description: 'Disclosure text shown on AI-generated posts',
        condition: (data) => data?.isAiGenerated === true,
      },
    },
    {
      name: 'content',
      type: 'richText',
      required: true,
    },
    {
      name: 'excerpt',
      type: 'textarea',
      admin: {
        description: 'Short summary for listings and SEO (auto-generated from content if empty)',
      },
    },
    {
      name: 'seo',
      type: 'group',
      fields: [
        {
          name: 'metaTitle',
          type: 'text',
        },
        {
          name: 'metaDescription',
          type: 'textarea',
        },
      ],
    },
  ],
}
