import { NextRequest } from 'next/server'
import { beforeEach,describe,expect,it,vi } from 'vitest'
import { handleGivingCheckoutPost,productionGivingCheckoutAuthority,resolveGivingCheckoutAuthority,type GivingCheckoutRouteDependencies } from './route'

const body={submissionKey:'A'.repeat(43),amountMinor:2500,fundId:1,frequency:'one-off',firstPaymentDate:null,firstName:'Ada',lastName:'Lovelace',email:'ada@example.com',turnstileToken:'token'}
function request(value:unknown=body,headers:Record<string,string>={}){return new NextRequest('https://www.ev.church/api/giving/checkouts',{method:'POST',headers:{origin:'https://www.ev.church','sec-fetch-site':'same-origin','x-ev-giving-request':'checkout-v1','content-type':'application/json',...headers},body:JSON.stringify(value)})}
function dependencies():GivingCheckoutRouteDependencies{ return {authority:vi.fn(async()=>({contextKey:'sandbox:e2e:r',environment:'sandbox' as const,synthetic:true,e2eRunId:1})),rateLimitStore:{increment:vi.fn(async()=>1)},verifyTurnstile:vi.fn(async()=>undefined),startCheckout:vi.fn(async()=>({outcome:'redirect' as const,gatewayRedirectUri:'https://sandbox.debit.blinkpay.co.nz/gateway',statusToken:'S'.repeat(43),correlationKey:'correlation',reused:false}))} }

describe('POST giving checkout',()=>{
  beforeEach(()=>vi.stubEnv('GIVING_RATE_LIMIT_SECRET','r'.repeat(32)))
  it('checks server authority before body, abuse controls and side effects',async()=>{const deps=dependencies();const response=await handleGivingCheckoutPost(request(),deps);expect(response.status).toBe(201);expect(deps.authority).toHaveBeenCalled();expect(vi.mocked(deps.authority).mock.invocationCallOrder[0]).toBeLessThan(vi.mocked(deps.rateLimitStore.increment).mock.invocationCallOrder[0]);expect(deps.verifyTurnstile).toHaveBeenCalled();expect(deps.startCheckout).toHaveBeenCalled();expect(response.headers.get('set-cookie')?.toLowerCase()).toContain('samesite=strict')})
  it('returns typed no-retry 202 and sets the status cookie for an ambiguous provider start',async()=>{const deps=dependencies();vi.mocked(deps.startCheckout).mockResolvedValue({outcome:'unknown',retryAllowed:false,statusToken:'U'.repeat(43),correlationKey:'correlation',reused:false});const response=await handleGivingCheckoutPost(request(),deps);expect(response.status).toBe(202);expect(await response.json()).toEqual({outcome:'unknown',retryAllowed:false,correlationKey:'correlation',reused:false});expect(response.headers.get('set-cookie')).toContain('U'.repeat(43))})
  it.each(['invalid','expired',''])('fails closed when an E2E cookie is present but %s instead of consulting production',async(e2eToken)=>{const readE2E=vi.fn(async()=>null);const loadProduction=vi.fn();await expect(resolveGivingCheckoutAuthority({e2eToken,readE2E,productionEnabled:'true',loadProduction})).resolves.toBeNull();expect(readE2E).toHaveBeenCalledWith(e2eToken);expect(loadProduction).not.toHaveBeenCalled()})
  it('rejects release-gated production and malformed authority before all downstream work',async()=>{const deps=dependencies();vi.mocked(deps.authority).mockResolvedValue(null);const response=await handleGivingCheckoutPost(request(),deps);expect(response.status).toBe(404);expect(deps.rateLimitStore.increment).not.toHaveBeenCalled();expect(deps.verifyTurnstile).not.toHaveBeenCalled();expect(deps.startCheckout).not.toHaveBeenCalled()})
  it('rejects production while any readiness diagnostic remains blocking',()=>{expect(productionGivingCheckoutAuthority({environment:'production',productionEnabled:true,readiness:[{code:'production-scopes',blocking:true,message:'unresolved'}]} as any)).toBeNull()})
  it.each([{header:{origin:'https://evil.test'} as Record<string,string>},{header:{'sec-fetch-site':'cross-site'} as Record<string,string>},{header:{'x-ev-giving-request':'copied'} as Record<string,string>}])('fails canonical origin, fetch metadata and CSRF before parsing',async({header})=>{const deps=dependencies();const response=await handleGivingCheckoutPost(request(body,header),deps);expect(response.status).toBe(403);expect(deps.rateLimitStore.increment).not.toHaveBeenCalled();expect(deps.startCheckout).not.toHaveBeenCalled()})
  it('rejects mass assignment and oversized JSON without provider work',async()=>{const deps=dependencies();const altered=await handleGivingCheckoutPost(request({...body,environment:'sandbox'}),deps);expect(altered.status).toBe(400);expect(deps.startCheckout).not.toHaveBeenCalled();const large=await handleGivingCheckoutPost(request(body,{'content-length':'9000'}),deps);expect(large.status).toBe(400)})
})
