'use client'

import { useRouter } from 'next/navigation'
import { useCallback, useEffect, useRef, useState } from 'react'

import type {
  VolunteerScheduleAssignment,
  VolunteerScheduleResult,
} from '@/lib/members/volunteer-scheduling'

const RETURN_REFRESH_THROTTLE_MS = 5_000
const REFRESH_FALLBACK_MS = 8_000

const occurrenceFormatter = new Intl.DateTimeFormat('en-NZ', {
  timeZone: 'Pacific/Auckland',
  weekday: 'long',
  day: 'numeric',
  month: 'long',
  year: 'numeric',
  hour: 'numeric',
  minute: '2-digit',
})

function AssignmentCard({
  assignment,
  state,
}: {
  assignment: VolunteerScheduleAssignment
  state: 'request' | 'confirmed'
}) {
  const supportingDetails = [assignment.scheduleName, assignment.locationName]
    .filter((value): value is string => Boolean(value))

  return (
    <article
      id={assignment.id}
      tabIndex={-1}
      className="scroll-mt-32 rounded-2xl border border-warm-grey bg-white p-6 shadow-sm shadow-brand-black/5 sm:p-7"
    >
      <p className="text-xs font-bold uppercase tracking-[0.16em] text-rich-red">
        {state === 'request' ? 'Response requested' : 'Confirmed'}
      </p>
      <h3 className="mt-3 text-2xl leading-tight text-brand-black">
        {assignment.title}
      </h3>
      <time
        dateTime={assignment.occurrenceStart}
        className="mt-4 block text-base font-bold text-dark-grey"
      >
        {occurrenceFormatter.format(new Date(assignment.occurrenceStart))}
      </time>
      {supportingDetails.length > 0 && (
        <p className="mt-2 text-sm leading-relaxed text-mid-grey">
          {supportingDetails.join(' · ')}
        </p>
      )}
    </article>
  )
}

export function VolunteerSchedule({
  schedule,
  isImpersonating,
}: {
  schedule: VolunteerScheduleResult
  isImpersonating: boolean
}) {
  const router = useRouter()
  const lastReturnRefreshAt = useRef(0)
  const refreshFallbackRef = useRef<number | null>(null)
  const refreshRequestedRef = useRef(false)
  const lastFocusedHashRef = useRef('')
  const previousRequestIdsRef = useRef(new Set(
    schedule.status === 'available' ? schedule.requests.map(({ id }) => id) : [],
  ))
  const [isRefreshing, setIsRefreshing] = useState(false)
  const [refreshFailed, setRefreshFailed] = useState(false)
  const [refreshAnnouncement, setRefreshAnnouncement] = useState('')

  const refreshCanonicalSchedule = useCallback(() => {
    const now = Date.now()
    if (now - lastReturnRefreshAt.current < RETURN_REFRESH_THROTTLE_MS) return
    lastReturnRefreshAt.current = now
    refreshRequestedRef.current = true
    setRefreshFailed(false)
    setIsRefreshing(true)
    router.refresh()
    if (refreshFallbackRef.current !== null) window.clearTimeout(refreshFallbackRef.current)
    refreshFallbackRef.current = window.setTimeout(() => {
      setIsRefreshing(false)
      setRefreshFailed(true)
    }, REFRESH_FALLBACK_MS)
  }, [router])

  useEffect(() => {
    setIsRefreshing(false)
    setRefreshFailed(false)
    if (refreshFallbackRef.current !== null) window.clearTimeout(refreshFallbackRef.current)
    if (schedule.status !== 'available') return

    const nextRequestIds = new Set(schedule.requests.map(({ id }) => id))
    if (refreshRequestedRef.current) {
      const removed = [...previousRequestIdsRef.current]
        .filter((id) => !nextRequestIds.has(id))
      if (removed.length > 0) {
        const movedToUpcoming = removed.some((id) =>
          schedule.upcoming.some((assignment) => assignment.id === id),
        )
        setRefreshAnnouncement(movedToUpcoming
          ? 'Your service response is confirmed and has moved to Upcoming.'
          : 'A service request is no longer available.')
      }
      refreshRequestedRef.current = false
    }
    previousRequestIdsRef.current = nextRequestIds
  }, [schedule])

  useEffect(() => () => {
    if (refreshFallbackRef.current !== null) window.clearTimeout(refreshFallbackRef.current)
  }, [])

  useEffect(() => {
    function focusScheduleTarget() {
      try {
        const hash = window.location.hash
        if (!hash) {
          lastFocusedHashRef.current = ''
          return
        }
        if (lastFocusedHashRef.current === hash) return
        const targetId = decodeURIComponent(hash.slice(1))
        const target = targetId.startsWith('rock-schedule:')
          ? document.getElementById(targetId)
          : null
        if (target) {
          target.focus()
          lastFocusedHashRef.current = hash
        }
      } catch {
        // Ignore malformed fragments that are not generated by the notification adapter.
      }
    }
    focusScheduleTarget()
    window.addEventListener('hashchange', focusScheduleTarget)
    return () => window.removeEventListener('hashchange', focusScheduleTarget)
  }, [schedule])

  useEffect(() => {
    const refreshWhenVisible = () => {
      if (document.visibilityState === 'visible') refreshCanonicalSchedule()
    }
    window.addEventListener('focus', refreshCanonicalSchedule)
    document.addEventListener('visibilitychange', refreshWhenVisible)
    return () => {
      window.removeEventListener('focus', refreshCanonicalSchedule)
      document.removeEventListener('visibilitychange', refreshWhenVisible)
    }
  }, [refreshCanonicalSchedule])

  if (schedule.status === 'unavailable') {
    return (
      <div
        role="alert"
        className="rounded-2xl border border-warm-grey bg-white p-7 sm:p-8"
      >
        <h2 className="text-2xl text-brand-black">Your schedule is temporarily unavailable</h2>
        <p className="mt-3 max-w-2xl text-sm leading-relaxed text-mid-grey">
          We could not safely load your current serving schedule from Rock. Please try again.
        </p>
        <button
          type="button"
          disabled={isRefreshing}
          onClick={refreshCanonicalSchedule}
          className="mt-5 min-h-11 rounded-full bg-rich-red px-5 py-2 text-sm font-bold text-white transition-colors hover:bg-brand-black focus:outline-none focus:ring-4 focus:ring-light-red-2"
        >
          {isRefreshing ? 'Refreshing…' : 'Retry'}
        </button>
      </div>
    )
  }

  const isCompletelyEmpty = schedule.requests.length === 0 && schedule.upcoming.length === 0

  return (
    <div className="space-y-10">
      <p aria-live="polite" role="status" className="sr-only">
        {refreshAnnouncement}
      </p>
      {isImpersonating && (
        <p role="status" className="rounded-xl border border-warm-grey bg-white px-5 py-4 text-sm text-dark-grey">
          This serving schedule is read-only while impersonating a member.
        </p>
      )}

      {isCompletelyEmpty && (
        <p className="rounded-2xl border border-warm-grey bg-white p-6 text-sm leading-relaxed text-mid-grey">
          You have no upcoming serving requests or commitments.
        </p>
      )}

      <section aria-labelledby="service-requests-heading">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <h2 id="service-requests-heading" className="text-3xl text-brand-black">Requests</h2>
            <p className="mt-2 max-w-2xl text-sm leading-relaxed text-mid-grey">
              Invitations waiting for your response.
            </p>
          </div>
        </div>

        {isRefreshing && (
          <p role="status" className="mt-4 text-sm font-bold text-dark-grey">
            Refreshing your current schedule…
          </p>
        )}

        {refreshFailed && (
          <div role="alert" className="mt-4 text-sm text-dark-grey">
            <p>We could not confirm your latest schedule. Refresh before responding.</p>
            <button
              type="button"
              onClick={refreshCanonicalSchedule}
              className="mt-2 min-h-11 font-bold text-rich-red"
            >
              Retry refresh
            </button>
          </div>
        )}

        {schedule.requests.length > 0 ? (
          <>
            {!isImpersonating && (
              <p className="mt-4 text-sm leading-relaxed text-dark-grey">
                Rock opens in a new tab so you can accept or decline these requests. Return here when you are done and this page will refresh from Rock.
              </p>
            )}
            <div className="mt-5 grid gap-4 lg:grid-cols-2">
              {schedule.requests.map((assignment) => (
                <AssignmentCard key={assignment.id} assignment={assignment} state="request" />
              ))}
            </div>
            {!isImpersonating && !isRefreshing && !refreshFailed && (
              <a
                href={schedule.nativeToolboxUrl}
                target="_blank"
                rel="nofollow noreferrer"
                className="mt-5 inline-flex min-h-11 items-center justify-center rounded-full bg-rich-red px-5 py-2 text-sm font-bold text-white transition-colors hover:bg-brand-black focus:outline-none focus:ring-4 focus:ring-light-red-2"
              >
                Respond in Rock
              </a>
            )}
          </>
        ) : (
          <p className="mt-5 rounded-2xl border border-warm-grey bg-white p-6 text-sm text-mid-grey">
            You have no serving requests to respond to.
          </p>
        )}
      </section>

      <section aria-labelledby="service-upcoming-heading">
        <h2 id="service-upcoming-heading" className="text-3xl text-brand-black">Upcoming</h2>
        <p className="mt-2 max-w-2xl text-sm leading-relaxed text-mid-grey">
          Serving commitments currently confirmed in Rock.
        </p>
        {schedule.upcoming.length > 0 ? (
          <div className="mt-5 grid gap-4 lg:grid-cols-2">
            {schedule.upcoming.map((assignment) => (
              <AssignmentCard key={assignment.id} assignment={assignment} state="confirmed" />
            ))}
          </div>
        ) : (
          <p className="mt-5 rounded-2xl border border-warm-grey bg-white p-6 text-sm text-mid-grey">
            You have no confirmed upcoming serving commitments.
          </p>
        )}
      </section>
    </div>
  )
}
