import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  // These enum changes auto-commit outside transactions, so use IF NOT EXISTS / DO blocks
  await db.execute(sql`
    DO $$ BEGIN
      CREATE TYPE "public"."enum_sermons_pipeline_status" AS ENUM('none', 'video-matched', 'transcribed', 'boundaries-set', 'blog-generated', 'complete', 'failed');
    EXCEPTION WHEN duplicate_object THEN NULL;
    END $$;
  `)

  await db.execute(sql`
    DO $$ BEGIN
      ALTER TYPE "public"."enum_payload_jobs_log_task_slug" ADD VALUE 'youtubeSync';
    EXCEPTION WHEN duplicate_object THEN NULL;
    END $$;
  `)

  await db.execute(sql`
    DO $$ BEGIN
      ALTER TYPE "public"."enum_payload_jobs_task_slug" ADD VALUE 'youtubeSync';
    EXCEPTION WHEN duplicate_object THEN NULL;
    END $$;
  `)

  await db.execute(sql`
  CREATE TABLE IF NOT EXISTS "sermons_videos" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"campus_id" integer NOT NULL,
  	"youtube_video_id" varchar NOT NULL,
  	"youtube_url" varchar NOT NULL,
  	"thumbnail_url" varchar
  );

  ALTER TABLE "blog_posts" ADD COLUMN IF NOT EXISTS "sermon_id" integer;
  ALTER TABLE "blog_posts" ADD COLUMN IF NOT EXISTS "is_ai_generated" boolean DEFAULT false;
  ALTER TABLE "blog_posts" ADD COLUMN IF NOT EXISTS "ai_disclosure" varchar DEFAULT 'This content was generated by AI from a sermon recording and reviewed for accuracy.';
  ALTER TABLE "_blog_posts_v" ADD COLUMN IF NOT EXISTS "version_sermon_id" integer;
  ALTER TABLE "_blog_posts_v" ADD COLUMN IF NOT EXISTS "version_is_ai_generated" boolean DEFAULT false;
  ALTER TABLE "_blog_posts_v" ADD COLUMN IF NOT EXISTS "version_ai_disclosure" varchar DEFAULT 'This content was generated by AI from a sermon recording and reviewed for accuracy.';
  ALTER TABLE "sermons" ADD COLUMN IF NOT EXISTS "sermon_start_seconds" numeric;
  ALTER TABLE "sermons" ADD COLUMN IF NOT EXISTS "sermon_end_seconds" numeric;
  ALTER TABLE "sermons" ADD COLUMN IF NOT EXISTS "boundaries_auto_detected" boolean DEFAULT false;
  ALTER TABLE "sermons" ADD COLUMN IF NOT EXISTS "boundaries_confirmed" boolean DEFAULT false;
  ALTER TABLE "sermons" ADD COLUMN IF NOT EXISTS "pipeline_status" "enum_sermons_pipeline_status" DEFAULT 'none';
  ALTER TABLE "sermons" ADD COLUMN IF NOT EXISTS "pipeline_error" varchar;
  ALTER TABLE "sermons" ADD COLUMN IF NOT EXISTS "blog_post_id" integer;
  ALTER TABLE "sermons" ADD COLUMN IF NOT EXISTS "ai_input_tokens" numeric;
  ALTER TABLE "sermons" ADD COLUMN IF NOT EXISTS "ai_output_tokens" numeric;`)

  // Constraints and indexes (use DO blocks to handle if they already exist)
  await db.execute(sql`
  DO $$ BEGIN
    ALTER TABLE "sermons_videos" ADD CONSTRAINT "sermons_videos_campus_id_campuses_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campuses"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$;

  DO $$ BEGIN
    ALTER TABLE "sermons_videos" ADD CONSTRAINT "sermons_videos_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."sermons"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$;

  CREATE INDEX IF NOT EXISTS "sermons_videos_order_idx" ON "sermons_videos" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "sermons_videos_parent_id_idx" ON "sermons_videos" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "sermons_videos_campus_idx" ON "sermons_videos" USING btree ("campus_id");

  DO $$ BEGIN
    ALTER TABLE "blog_posts" ADD CONSTRAINT "blog_posts_sermon_id_sermons_id_fk" FOREIGN KEY ("sermon_id") REFERENCES "public"."sermons"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$;

  DO $$ BEGIN
    ALTER TABLE "_blog_posts_v" ADD CONSTRAINT "_blog_posts_v_version_sermon_id_sermons_id_fk" FOREIGN KEY ("version_sermon_id") REFERENCES "public"."sermons"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$;

  DO $$ BEGIN
    ALTER TABLE "sermons" ADD CONSTRAINT "sermons_blog_post_id_blog_posts_id_fk" FOREIGN KEY ("blog_post_id") REFERENCES "public"."blog_posts"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$;

  CREATE INDEX IF NOT EXISTS "blog_posts_sermon_idx" ON "blog_posts" USING btree ("sermon_id");
  CREATE INDEX IF NOT EXISTS "_blog_posts_v_version_version_sermon_idx" ON "_blog_posts_v" USING btree ("version_sermon_id");
  CREATE INDEX IF NOT EXISTS "sermons_blog_post_idx" ON "sermons" USING btree ("blog_post_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "sermons_videos" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "sermons_videos" CASCADE;
  ALTER TABLE "blog_posts" DROP CONSTRAINT IF EXISTS "blog_posts_sermon_id_sermons_id_fk";
  ALTER TABLE "_blog_posts_v" DROP CONSTRAINT IF EXISTS "_blog_posts_v_version_sermon_id_sermons_id_fk";
  ALTER TABLE "sermons" DROP CONSTRAINT IF EXISTS "sermons_blog_post_id_blog_posts_id_fk";
  ALTER TABLE "payload_jobs_log" ALTER COLUMN "task_slug" SET DATA TYPE text;
  DROP TYPE "public"."enum_payload_jobs_log_task_slug";
  CREATE TYPE "public"."enum_payload_jobs_log_task_slug" AS ENUM('inline', 'fullSermonSync');
  ALTER TABLE "payload_jobs_log" ALTER COLUMN "task_slug" SET DATA TYPE "public"."enum_payload_jobs_log_task_slug" USING "task_slug"::"public"."enum_payload_jobs_log_task_slug";
  ALTER TABLE "payload_jobs" ALTER COLUMN "task_slug" SET DATA TYPE text;
  DROP TYPE "public"."enum_payload_jobs_task_slug";
  CREATE TYPE "public"."enum_payload_jobs_task_slug" AS ENUM('inline', 'fullSermonSync');
  ALTER TABLE "payload_jobs" ALTER COLUMN "task_slug" SET DATA TYPE "public"."enum_payload_jobs_task_slug" USING "task_slug"::"public"."enum_payload_jobs_task_slug";
  DROP INDEX IF EXISTS "blog_posts_sermon_idx";
  DROP INDEX IF EXISTS "_blog_posts_v_version_version_sermon_idx";
  DROP INDEX IF EXISTS "sermons_blog_post_idx";
  ALTER TABLE "blog_posts" DROP COLUMN IF EXISTS "sermon_id";
  ALTER TABLE "blog_posts" DROP COLUMN IF EXISTS "is_ai_generated";
  ALTER TABLE "blog_posts" DROP COLUMN IF EXISTS "ai_disclosure";
  ALTER TABLE "_blog_posts_v" DROP COLUMN IF EXISTS "version_sermon_id";
  ALTER TABLE "_blog_posts_v" DROP COLUMN IF EXISTS "version_is_ai_generated";
  ALTER TABLE "_blog_posts_v" DROP COLUMN IF EXISTS "version_ai_disclosure";
  ALTER TABLE "sermons" DROP COLUMN IF EXISTS "sermon_start_seconds";
  ALTER TABLE "sermons" DROP COLUMN IF EXISTS "sermon_end_seconds";
  ALTER TABLE "sermons" DROP COLUMN IF EXISTS "boundaries_auto_detected";
  ALTER TABLE "sermons" DROP COLUMN IF EXISTS "boundaries_confirmed";
  ALTER TABLE "sermons" DROP COLUMN IF EXISTS "pipeline_status";
  ALTER TABLE "sermons" DROP COLUMN IF EXISTS "pipeline_error";
  ALTER TABLE "sermons" DROP COLUMN IF EXISTS "blog_post_id";
  ALTER TABLE "sermons" DROP COLUMN IF EXISTS "ai_input_tokens";
  ALTER TABLE "sermons" DROP COLUMN IF EXISTS "ai_output_tokens";
  DROP TYPE IF EXISTS "public"."enum_sermons_pipeline_status";`)
}
