import type { MigrateDownArgs, MigrateUpArgs } from '@payloadcms/db-postgres'
import { sql } from '@payloadcms/db-postgres'

const TABLES = ['giving_funds','giving_e2e_runs','giving_givers','giving_checkouts','giving_gifts','giving_consents','giving_schedules','giving_provider_operations','blinkpay_webhook_events'] as const

export const GIVING_PILOT_UP_SQL = String.raw`
SET LOCAL lock_timeout = '5s'; SET LOCAL statement_timeout = '60s';
CREATE TABLE IF NOT EXISTS "giving_funds" ("id" serial PRIMARY KEY,"name" varchar NOT NULL,"code" varchar NOT NULL UNIQUE,"accounting_key" varchar NOT NULL,"description" varchar,"active" boolean NOT NULL DEFAULT true,"is_default" boolean NOT NULL DEFAULT false,"sort_order" numeric NOT NULL DEFAULT 0,"updated_at" timestamptz NOT NULL DEFAULT now(),"created_at" timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX giving_funds_one_default ON giving_funds ((true)) WHERE is_default AND active;
CREATE OR REPLACE FUNCTION giving_funds_require_default() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF EXISTS(SELECT 1 FROM giving_funds) AND NOT EXISTS(SELECT 1 FROM giving_funds WHERE is_default AND active) THEN RAISE EXCEPTION 'Giving funds require exactly one active default'; END IF; RETURN NULL; END $$;
CREATE CONSTRAINT TRIGGER giving_funds_require_default AFTER INSERT OR UPDATE OR DELETE ON giving_funds DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION giving_funds_require_default();
CREATE TABLE IF NOT EXISTS "giving_e2e_runs" ("id" serial PRIMARY KEY,"run_id" varchar NOT NULL UNIQUE,"context_key" varchar NOT NULL UNIQUE,"environment" varchar NOT NULL DEFAULT 'sandbox',"synthetic" boolean NOT NULL DEFAULT true,"actor_id" integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,"token_digest" varchar NOT NULL UNIQUE,"expires_at" timestamptz NOT NULL,"revoked_at" timestamptz,"updated_at" timestamptz NOT NULL DEFAULT now(),"created_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT giving_e2e_run_context_valid CHECK(environment='sandbox' AND synthetic AND context_key=('sandbox:e2e:' || run_id)));
CREATE TABLE IF NOT EXISTS "giving_givers" ("id" serial PRIMARY KEY,"context_key" varchar NOT NULL,"environment" varchar NOT NULL,"synthetic" boolean NOT NULL,"e2e_run_id" integer REFERENCES giving_e2e_runs(id) ON DELETE RESTRICT,"rock_person_alias_id" numeric NOT NULL,"bank_reference" varchar NOT NULL,"name" varchar NOT NULL,"email" varchar NOT NULL,"updated_at" timestamptz NOT NULL DEFAULT now(),"created_at" timestamptz NOT NULL DEFAULT now(),UNIQUE(context_key,rock_person_alias_id),UNIQUE(id,context_key));
CREATE TABLE IF NOT EXISTS "giving_checkouts" ("id" serial PRIMARY KEY,"context_key" varchar NOT NULL,"environment" varchar NOT NULL,"synthetic" boolean NOT NULL,"e2e_run_id" integer REFERENCES giving_e2e_runs(id) ON DELETE RESTRICT,"giver_id" integer,"fund_id" integer NOT NULL REFERENCES giving_funds(id) ON DELETE RESTRICT,"fund_name" varchar NOT NULL,"fund_code" varchar NOT NULL,"fund_accounting_key" varchar NOT NULL,"amount_minor" numeric NOT NULL,"frequency" varchar NOT NULL CHECK(frequency IN ('one-off','daily','weekly','fortnightly','monthly','annual')),"first_payment_date" timestamptz,"correlation_key" varchar NOT NULL UNIQUE,"status" varchar NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','authorising','verifying','unknown','completed','failed')),"updated_at" timestamptz NOT NULL DEFAULT now(),"created_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT amount_minor_positive_integer CHECK(amount_minor > 0 AND amount_minor <= 9007199254740991 AND amount_minor = trunc(amount_minor)),FOREIGN KEY(giver_id,context_key) REFERENCES giving_givers(id,context_key) ON DELETE RESTRICT,UNIQUE(id,context_key));
CREATE TABLE IF NOT EXISTS "giving_gifts" ("id" serial PRIMARY KEY,"context_key" varchar NOT NULL,"environment" varchar NOT NULL,"synthetic" boolean NOT NULL,"e2e_run_id" integer REFERENCES giving_e2e_runs(id) ON DELETE RESTRICT,"checkout_id" integer NOT NULL,"giver_id" integer NOT NULL,"fund_id" integer NOT NULL REFERENCES giving_funds(id) ON DELETE RESTRICT,"fund_name" varchar NOT NULL,"fund_code" varchar NOT NULL,"fund_accounting_key" varchar NOT NULL,"amount_minor" numeric NOT NULL,"provider_payment_id" varchar NOT NULL,"status" varchar NOT NULL,"provider_observed_at" timestamptz,"provider_request_id" varchar,"updated_at" timestamptz NOT NULL DEFAULT now(),"created_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT amount_minor_positive_integer_gift CHECK(amount_minor > 0 AND amount_minor <= 9007199254740991 AND amount_minor=trunc(amount_minor)),CONSTRAINT giving_gifts_payment_unique UNIQUE(environment,provider_payment_id),CONSTRAINT giving_gifts_checkout_unique UNIQUE(checkout_id),FOREIGN KEY(checkout_id,context_key) REFERENCES giving_checkouts(id,context_key),FOREIGN KEY(giver_id,context_key) REFERENCES giving_givers(id,context_key));
CREATE TABLE IF NOT EXISTS "giving_consents" ("id" serial PRIMARY KEY,"context_key" varchar NOT NULL,"environment" varchar NOT NULL,"synthetic" boolean NOT NULL,"e2e_run_id" integer REFERENCES giving_e2e_runs(id) ON DELETE RESTRICT,"checkout_id" integer NOT NULL,"giver_id" integer NOT NULL,"provider_consent_id" varchar NOT NULL,"status" varchar NOT NULL,"provider_observed_at" timestamptz,"provider_request_id" varchar,"updated_at" timestamptz NOT NULL DEFAULT now(),"created_at" timestamptz NOT NULL DEFAULT now(),UNIQUE(environment,provider_consent_id),UNIQUE(id,context_key),FOREIGN KEY(checkout_id,context_key) REFERENCES giving_checkouts(id,context_key),FOREIGN KEY(giver_id,context_key) REFERENCES giving_givers(id,context_key));
CREATE TABLE IF NOT EXISTS "giving_schedules" ("id" serial PRIMARY KEY,"context_key" varchar NOT NULL,"environment" varchar NOT NULL,"synthetic" boolean NOT NULL,"e2e_run_id" integer REFERENCES giving_e2e_runs(id) ON DELETE RESTRICT,"checkout_id" integer NOT NULL,"giver_id" integer NOT NULL,"consent_id" integer NOT NULL,"provider_schedule_id" varchar NOT NULL,"status" varchar NOT NULL CHECK(status IN ('pending','active','unknown','cancel_pending','cancelled','failed')),"frequency" varchar NOT NULL,"amount_minor" numeric NOT NULL,"next_payment_date" timestamptz,"provider_observed_at" timestamptz,"provider_request_id" varchar,"updated_at" timestamptz NOT NULL DEFAULT now(),"created_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT giving_schedules_consent_unique UNIQUE(consent_id),UNIQUE(environment,provider_schedule_id),CONSTRAINT amount_minor_positive_integer_schedule CHECK(amount_minor>0 AND amount_minor <= 9007199254740991 AND amount_minor=trunc(amount_minor)),FOREIGN KEY(checkout_id,context_key) REFERENCES giving_checkouts(id,context_key),FOREIGN KEY(giver_id,context_key) REFERENCES giving_givers(id,context_key),FOREIGN KEY(consent_id,context_key) REFERENCES giving_consents(id,context_key));
CREATE TABLE IF NOT EXISTS "giving_provider_operations" ("id" serial PRIMARY KEY,"context_key" varchar NOT NULL,"environment" varchar NOT NULL,"synthetic" boolean NOT NULL,"e2e_run_id" integer REFERENCES giving_e2e_runs(id) ON DELETE RESTRICT,"checkout_id" integer NOT NULL,"provider" varchar NOT NULL,"action" varchar NOT NULL,"logical_version" numeric NOT NULL,"request_digest" varchar NOT NULL,"correlation_key" varchar NOT NULL,"status" varchar NOT NULL CHECK(status IN ('prepared','submitted','succeeded','unknown','failed')),"provider_id" varchar,"provider_request_id" varchar,"updated_at" timestamptz NOT NULL DEFAULT now(),"created_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT giving_provider_operations_semantic_unique UNIQUE(checkout_id,provider,action,logical_version),FOREIGN KEY(checkout_id,context_key) REFERENCES giving_checkouts(id,context_key));
CREATE UNIQUE INDEX giving_provider_operations_provider_id_unique ON giving_provider_operations(environment,provider,provider_id) WHERE provider_id IS NOT NULL;
CREATE UNIQUE INDEX giving_provider_operations_unresolved_unique ON giving_provider_operations(checkout_id,provider,action) WHERE status IN ('prepared','submitted','unknown');
CREATE OR REPLACE FUNCTION giving_provider_requires_identity() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.provider='blinkpay' AND NOT EXISTS(SELECT 1 FROM giving_checkouts WHERE id=NEW.checkout_id AND context_key=NEW.context_key AND giver_id IS NOT NULL) THEN RAISE EXCEPTION 'BlinkPay operations require a bound giver'; END IF; RETURN NEW; END $$;
CREATE TRIGGER giving_provider_requires_identity BEFORE INSERT ON giving_provider_operations FOR EACH ROW EXECUTE FUNCTION giving_provider_requires_identity();
CREATE TABLE IF NOT EXISTS "giving_provider_operation_attempts" ("id" bigserial PRIMARY KEY,"operation_id" integer NOT NULL REFERENCES giving_provider_operations(id) ON DELETE RESTRICT,"attempt_number" integer NOT NULL CHECK(attempt_number > 0),"outcome" varchar NOT NULL,"provider_request_id" varchar,"error_code" varchar,"attempted_at" timestamptz NOT NULL DEFAULT now(),CONSTRAINT giving_provider_operation_attempts_number_unique UNIQUE(operation_id,attempt_number));
CREATE OR REPLACE FUNCTION giving_attempts_append_only() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Provider operation attempts are append-only'; END $$;
CREATE TRIGGER giving_attempts_append_only BEFORE UPDATE OR DELETE ON giving_provider_operation_attempts FOR EACH ROW EXECUTE FUNCTION giving_attempts_append_only();
CREATE TABLE IF NOT EXISTS "blinkpay_webhook_events" ("id" serial PRIMARY KEY,"context_key" varchar NOT NULL,"environment" varchar NOT NULL,"synthetic" boolean NOT NULL,"e2e_run_id" integer REFERENCES giving_e2e_runs(id) ON DELETE RESTRICT,"provider_event_id" varchar NOT NULL,"event_type" varchar NOT NULL,"payload_digest" varchar NOT NULL,"payload" jsonb NOT NULL,"status" varchar NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','processing','retry','processed','quarantined','dead')),"next_attempt_at" timestamptz,"lease_token" uuid,"lease_expires_at" timestamptz,"attempt_count" numeric NOT NULL DEFAULT 0,"duplicate_count" numeric NOT NULL DEFAULT 0,"conflict_count" numeric NOT NULL DEFAULT 0,"last_duplicate_at" timestamptz,"last_conflict_at" timestamptz,"processed_at" timestamptz,"last_error" varchar,"updated_at" timestamptz NOT NULL DEFAULT now(),"created_at" timestamptz NOT NULL DEFAULT now(),UNIQUE(environment,provider_event_id),CONSTRAINT blinkpay_webhook_events_lease_valid CHECK((status='processing' AND lease_token IS NOT NULL AND lease_expires_at IS NOT NULL) OR (status<>'processing' AND lease_token IS NULL AND lease_expires_at IS NULL)));
CREATE INDEX blinkpay_webhook_events_claim_idx ON blinkpay_webhook_events(status,next_attempt_at,created_at) WHERE status IN ('pending','retry');
CREATE INDEX blinkpay_webhook_events_expired_lease_idx ON blinkpay_webhook_events(lease_expires_at) WHERE status='processing';
ALTER TABLE giving_e2e_runs ADD CONSTRAINT giving_e2e_runs_id_context_unique UNIQUE(id,context_key);
${['giving_givers','giving_checkouts','giving_gifts','giving_consents','giving_schedules','giving_provider_operations','blinkpay_webhook_events'].map((t) => `ALTER TABLE ${t} ADD CONSTRAINT ${t}_provenance_valid CHECK((environment='production' AND NOT synthetic AND e2e_run_id IS NULL AND context_key='production') OR (environment='sandbox' AND synthetic AND e2e_run_id IS NOT NULL)); ALTER TABLE ${t} ADD CONSTRAINT ${t}_e2e_context_fk FOREIGN KEY(e2e_run_id,context_key) REFERENCES giving_e2e_runs(id,context_key) ON DELETE RESTRICT;`).join('\n')}
ALTER TABLE payload_locked_documents_rels ${TABLES.map((t) => `ADD COLUMN IF NOT EXISTS "${t}_id" integer`).join(',')};
${TABLES.map((t) => `DO $$ BEGIN ALTER TABLE payload_locked_documents_rels ADD CONSTRAINT payload_locked_documents_rels_${t}_fk FOREIGN KEY ("${t}_id") REFERENCES "${t}"(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$; CREATE INDEX IF NOT EXISTS payload_locked_documents_rels_${t}_id_idx ON payload_locked_documents_rels("${t}_id");`).join('\n')}
`

export const GIVING_PILOT_DOWN_SQL = String.raw`
SET LOCAL lock_timeout='5s'; SET LOCAL statement_timeout='60s';
DO $$ BEGIN IF EXISTS(SELECT 1 FROM giving_funds UNION ALL SELECT 1 FROM giving_e2e_runs UNION ALL SELECT 1 FROM giving_givers UNION ALL SELECT 1 FROM giving_checkouts UNION ALL SELECT 1 FROM giving_gifts UNION ALL SELECT 1 FROM giving_consents UNION ALL SELECT 1 FROM giving_schedules UNION ALL SELECT 1 FROM giving_provider_operations UNION ALL SELECT 1 FROM blinkpay_webhook_events LIMIT 1) THEN RAISE EXCEPTION 'Cannot roll back giving pilot after giving data exists'; END IF; END $$;
${[...TABLES].reverse().map((t) => `DROP INDEX IF EXISTS payload_locked_documents_rels_${t}_id_idx; ALTER TABLE payload_locked_documents_rels DROP CONSTRAINT IF EXISTS payload_locked_documents_rels_${t}_fk; ALTER TABLE payload_locked_documents_rels DROP COLUMN IF EXISTS "${t}_id";`).join('\n')}
DROP TRIGGER IF EXISTS giving_attempts_append_only ON giving_provider_operation_attempts; DROP FUNCTION IF EXISTS giving_attempts_append_only(); DROP TABLE IF EXISTS giving_provider_operation_attempts;
DROP TRIGGER IF EXISTS giving_provider_requires_identity ON giving_provider_operations; DROP FUNCTION IF EXISTS giving_provider_requires_identity(); DROP TRIGGER IF EXISTS giving_funds_require_default ON giving_funds; DROP FUNCTION IF EXISTS giving_funds_require_default();
${[...TABLES].reverse().map((t) => `DROP TABLE IF EXISTS "${t}";`).join('\n')}
`

export async function up({ db }: MigrateUpArgs) { await db.execute(sql.raw(GIVING_PILOT_UP_SQL)) }
export async function down({ db }: MigrateDownArgs) { await db.execute(sql.raw(GIVING_PILOT_DOWN_SQL)) }
