import { describe, expect, it, vi } from 'vitest'
import { readBlocks, verifyScripture, toLexical } from './content'
vi.mock('@/lib/api-bible', () => ({ fetchApiBibleCSBPassage: vi.fn(async () => ({ reference: 'John 1:1', content: 'Verified passage', copyright: 'CSB copyright', fumsToken: 'view-token' })) }))
describe('article Scripture boundary', () => {
  it('discards supplied quote wording and inserts only provider text', async () => {
    const blocks = await verifyScripture(readBlocks([{ type: 'scripture', reference: 'John 1:1', text: 'Invented quote', copyright: 'fake' }]))
    expect(blocks).toEqual([{ type: 'scripture', reference: 'John 1:1', text: 'Verified passage', copyright: 'CSB copyright', fumsToken: 'view-token' }])
    const content = JSON.stringify(toLexical(blocks))
    expect(content).toContain('Verified passage')
    expect(content).toContain('John 1:1 (CSB)')
    expect(content).not.toContain('Invented quote')
    expect(content).not.toContain('generated by AI')
  })
  it('preserves prose and headings as text, never HTML', () => {
    const lexical = toLexical(readBlocks([{ type: 'heading', text: 'The hope we have' }, { type: 'paragraph', text: '<script>example</script>' }]))
    expect(lexical.root.children[0]).toMatchObject({ type: 'heading', tag: 'h2' })
    expect(lexical.root.children[1]).toMatchObject({ type: 'paragraph', children: [{ type: 'text', text: '<script>example</script>' }] })
  })
  it.each([null, [], [{ type: 'html', text: 'unsafe' }], [{ type: 'paragraph', text: '' }]])('rejects malformed or empty articles', (value) => expect(() => readBlocks(value)).toThrow())
})
